### ISSUE TITLE
Project Delivery Tracker List 정적화면 및 리스트 구현

### ISSUE THREAD

**Issue by Jeongsoheeme** [Develog-Tools-for-team-productivity/Develog-V2#9]
# To Do Check List
- [ ]  **ProjectDeliveryTracker 정적화면 구현**
- [ ]  **ProjectDeliveryTracker TeamView 데이터 할당하기**
- [ ]  **ProjectDeliveryTracker 리스트 데이터 할당**
 
# Mock up

- ProjectDeliveryTracker
![Image](https://github.com/user-attachments/assets/13552260-cffe-4b6a-9681-f490e3258045)

# Description
- ProjectDeliveryTracker 데이터를 가져와서 숫자와 차트로 시각화한다.
-
